
set nocompatible
" remeber the position of last exit
if has("autocmd")
    au BufReadPost * if line("'\"") > 0 && line("'\"") <= line("$")
     \| exe "normal g'\"" | endif
endif

"source $VIMRUNTIME/vimrc_example.vim
"source $VIMRUNTIME/mswin.vim
"behave mswin
set encoding=utf-8
set fileencodings=utf-8,gbk

colorscheme desert
filetype plugin on
set number
set nobackup
set hlsearch
set incsearch
set ignorecase
set cursorline
syntax on

call plug#begin('~/.vim/plugged')
Plug 'Valloric/YouCompleteMe'
Plug 'haya14busa/incsearch.vim'
Plug 'godlygeed/tabular'
call plug#end()

