# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="af-magic"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git autojump tmux tmuxinator)

# User configuration

export PATH=$HOME/steel/install/nvim:$HOME/steel/working/uav/px4/toolchain/bin:$HOME/steel/install/bc3/bin/:$HOME/install/arduino-1.6.5:$HOME/bin:/usr/local/bin:$HOME/steel/working/tbea/u-boot/tools/:$PATH
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
export REPOS=http://172.24.105.209/repos
export EDITOR='vim'
export NFS_BOOT=~/steel/working/tbea/buildroot/output/rootfs/boot/
source ~/steel/working/repos/tmuxinator/completion/tmuxinator.zsh
source ~/.oh-my-zsh/plugins/k/k.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"
alias mgrep="grep -i -n -r --color "
alias mfgrep='find . -name "*.[chS]" | xargs grep -i -n --color'
alias cboot='cp ~/working/tbea/rootfs/boot/MLO /media/liugang/BOOT/;cp ~/working/tbea/rootfs/boot/u-boot.img /media/liugang/BOOT/'
alias tmw='mux start working'
alias impact='/home/steel/steel/install/ise/14.7/LabTools/LabTools/bin/lin64/impact'
alias cscope='/home/steel/steel/install/ise/14.7/LabTools/LabTools/bin/lin64/analyzer
alias ise='/home/steel/steel/install/ise/14.7/ISE_DS/ISE/bin/lin64/ise

alias cpm='cp -f ~/steel/working/tbea/zlg3352/drivers/gpmc/ext_mem.ko /media/steel/MYBOOT/waverec/'
#alias cpa='cp -f ~/steel/working/tbea/apps/waverec/bin/waverec /media/steel/2C04-61BB/waverec/; cp -f ~/steel/working/tbea/zlg3352/drivers/gpmc/fpga_mem.ko /media/steel/2C04-61BB/waverec/'
alias cpa='cp -f ~/steel/working/tbea/apps/waverec/bin/waverec /media/steel/0012-D687/waverec/; cp -f ~/steel/working/tbea/zlg3352/drivers/gpmc/fpga_mem.ko /media/steel/0012-D687/waverec/'
alias cng='cd /media/steel/WORK/steel/working/lingying/new_git/'

